// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raperkoduhtqcpnbcwbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcGVya29kdWh0cWNwbmJjd2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzY0MTgsImV4cCI6MjA3NDA1MjQxOH0.SnkeZpK34PTSgS9KsqxzSroP4_QXig9A4Ee0bQZHtzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});